<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>EnhancedCursor</AssemblyName>
    <OutputPath>bin\Release</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <KSPDirectory>D:\Steam\steamapps\common\Kerbal Space Program</KSPDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
	<Reference Include="UnityEngine.ImageConversionModule">
	  <HintPath>$(KSPDirectory)\KSP_x64_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
	</Reference>
	<Reference Include="0Harmony">
	  <HintPath>$(KSPDirectory)\Gamedata\000_Harmony\0Harmony.dll</HintPath>
	</Reference>
  </ItemGroup>
</Project>
